### ISSUE TITLE
 SQL/MED implementations moved from ambry use old format of the partitions. Convert to new.

### ISSUE THREAD

**Issue by nmb10** [CivicKnowledge/ambry_sources#1]
**Q. Did you change format of a partition msgpack file?**
A. Yes. There is a header ( 38 bytes ) then the rows. After the rows is a dict for metadata. 
The Cursor.Next() function, for Sqlite should use the row iterator: 
```python
f = MPRowsFile(…)
r = f.reader
itr = iter(r.rows)
…
r.close()
```
You can also use it in a context:
```python
with f.reader as r:
	for row in r.rows:
		yield rows
```

**Q. How to get column names and types for sql tables from msgpack file?**
A.
```python
f = MPRowsFile(...)
f.schema
```

**Q. How to generate new packed partition files (MPR) for testing?**
A. See test/test_basic.py: test_row_load_intuit(). That test generates a set of sufficiently complex files.

**Comment by nmb10** [comment]
Q. Column schema does not have length property of the type='str'. What length should I use while creating database table? I'm talking about 'create table ...' query.

Q. What is the convention to name virtual tables of the partitions? Now I use 
```python
table_name = '_'.join(MPRowsFile(...).headers)
```
but it will fail often. Can we do better?

Q. I met unclear behaviour of a MPRowsFile. I wrote tests for that and commented my doubts there. Can you review and comment them? 
  tests/test_med/unit/test_temp.py::Test::test_column_recoginized_as_int_loads_as_str
  tests/test_med/unit/test_temp.py::Test::test_row_intuiter_invented_columns
If they are bugs, I'll created issues for both.

Thank you.

**Comment by ericbusboom** [comment]
**Q. Column schema does not have length property of the type='str'. What length should I use while creating database table? I'm talking about 'create table ...' query.***

Just make them TEXT.  In postgres, the performance different is negligible vs using lengths, and in sqlite, all of the string types are just TEXT

**Q. What is the convention to name virtual tables of the partitions? Now I use**. 

If you have code to make the table from only a reference to the MPRRowsFile, and random character string will do. 

However, the production use will have the foreign tables definition created from the main Ambry module, where the schema is available, so the table name will be the name of the partition, or its vid number. 

**Q. I met unclear behaviour of a MPRowsFile. I wrote tests for that and commented my doubts there. Can you review and comment them? ** 

Ok, I'll comment the lines.

**Comment by ericbusboom** [comment]
Arg, I can comments them if they aren't in a commit .... 


    21 spec = SourceSpec('http://example.com', expect_start='2', name='test', expect_headers='1')

You should be able to make this a real source, and get rid of the manual invocation of DelayedOpen and CsvSource. Just use a file path in the SourceSpec. You may have to alter the download routine to prevent it downloading. 

Also, the "expect_start" and "expect_headers" are used only for testing, so you can specify the values that you expect the RowIntuiter to produce. 

When you load from a CSV file, I think all of the values are strings until you cast them to something else. Other file formats, like Excel, will preserve the type. 

So, there may need to be a casting operation ( like ambry.etl.Caster ) on the output of the MPR file. Or maybe, if a schema is defined, a casting operating on the input. Would something like that address this issue?

I'm not sure about the issue with test_row_intuiter_invented_columns, but perhaps it has something to do with the 'expect_start' and 'expect_headers' being only for testing. That means the SourceSpec does not specify what the header row for the file is, so it just creates a header from column positions.

**Comment by nmb10** [comment]
Q. What is the convention to name virtual tables of the partitions? Now I use...

A. If you have code to make the table from only a reference to the MPRRowsFile, and random character string will do.
..
Q. Yes, I create table from MPRRowsFile instance. If I'll use random string, how will we query table later? Look at example:
```python
# create many partitions with random table names.
add_partition(connection, mpr1)
add_partition(connection, mpr2)
add_partition(connection, mpr3)
```
Now we want to query mpr2 file. How could we find name of the created table? If I'll use random str I'll need to bind genereted table name to mpr file. I think better thing is to find (create) any unique value and keep it with mpr file (for me partition.path looks unique, but I'm not sure). Is it possible?

**Comment by ericbusboom** [comment]
```
# create many partitions with random table names.
add_partition(connection, mpr1)
```

Make it: 

```
def add_partition(connection, file, name=None)
```

Then

```
# Define the name 
add_partition(connection, mpr1, 'partition_name')

#Use the random name
random_name = add_partition(connection, mpr1)
```

**Comment by nmb10** [comment]
But this makes impossible to query tables later, from another process for example. Here is an example:
  User1 adds partition (creates table). The created table has random name.
  User2 wants to query table created by User1. How could User2 know table name?

**Comment by ericbusboom** [comment]
> On Sep 16, 2015, at 10:33 AM, Kazbek <notifications@github.com> wrote:
> 
> But this makes impossible to query tables later, from another process for example. Here is an example:
> User1 adds partition (creates table). The created table has random name.
> User2 wants to query table created by User1. How could User2 know table name?

That’s OK, because when Ambry creates the table, it will be called from code that has access to all of the metadata, so it will set the name to the vid of the partition. Those values are well-known. 

The random name generation is really only needed for testing within the ambry_sources package, and there, you don’t need to work across multiple processes. 

eric. 

----------------------------------------------------------------------------------------------------------
Eric Busboom                                                                                (619) 363 2607        
eric@busboom.org                                                         http://www.busboom.org

**Comment by nmb10** [comment]
Done. I added required vid parameter to the add_partition function. Also both implementations provides helpers to get name of the table by vid - get_name(vid).
