### ISSUE TITLE
Port ambry_sources to py3.

### ISSUE THREAD

**Issue by nmb10** [CivicKnowledge/ambry_sources#14]

**Comment by nmb10** [comment]
Done. Waiting on pypi continue with ambry porting.

**Comment by ericbusboom** [comment]
> On Oct 14, 2015, at 10:45 AM, Kazbek <notifications@github.com> wrote:
> 
> Done. Waiting on pypi continue with ambry porting.

Excellent, thanks, I’ll update ambry_sources now.  But, why does pypi have to be updated? Can you put ambry_sources  source into the same virtenv as ambry, and install it from git?

eric. 

----------------------------------------------------------------------------------------------------------
Eric Busboom                                                                                (619) 363 2607        
eric@busboom.org                                                         http://www.busboom.org

**Comment by nmb10** [comment]
I can, but it simplifies update for other users.

**Comment by ericbusboom** [comment]
> On Oct 14, 2015, at 11:23 PM, Kazbek <notifications@github.com> wrote:
> 
> I can, but it simplifies update for other users.

Very true, but there aren’t any other users yet.  They are still on the old version. I’ll move them over in probably two months. 

eric. 


----------------------------------------------------------------------------------------------------------
Eric Busboom                                                                                (619) 363 2607        
eric@busboom.org                                                         http://www.busboom.org
