### ISSUE TITLE
Implement HDF5 format files with MPR Interface

### ISSUE THREAD

**Issue by ericbusboom** [CivicKnowledge/ambry_sources#16]
( This is a quick overview, not the whole spec, since I didn't get a chance to fully spec it today ) 

Implement a new version of the MPR file objects, using HDF, via the PyTables library. THese files would be used for that partitions, while the mpr files will continue to be used for ingestion. 

The new HDF file objects should have the same interface as the MPR files, and most of the same tests should pass. The most important differences are: 

* In HDF, there is only one data type per column. 
* MPR files can have the header lines and data lines start on any line, not just 0 and 1, while for HDF, there is no header line, and the data always starts on line 0. 

The HDF files will not need to support row intuition or type intuition, since those will always be know at the time of file creation, but they will need to support statistics. 

Unlike the current MPR file, HDF files can't store a NULL in a data column. This is a requirement for our use. To handle this, 

* For floats, use NaN for null
* For integers, use the minimum storable integer as a NULL.
* For strings, use the empty string. 

Then, update the RowProxy object so that it can (1) have a sense of what the dataypes are per column, and (2) for each of the columns, interpret the NULL place holder value and return a null. For instance, for a float column, the RowProxy should return a None when the stores value is a NaN. 

Note: It may be really hard to dynamically generate tables in PyTables; it looks like they are designed to be specified as Python classes. If so, consider using the h5py package instead, although it may be very difficult to handle the queries without PyTable.

**Comment by ericbusboom** [comment]
Performance Tests

Once you get basic reading and writing working, can you add a performance test for the HDF version to: tests.test_basic.BasicTestSuite#test_datafile_read_write. Getting a sense of the performance differences  will be important to determine whether we should finish this feature now, or delay it for later.

**Comment by nmb10** [comment]
I added performance test:
```bash
py.test  tests/test_hdf_partitions/performance/test.py::Test::test_datafile_read_write  --capture=no
```
HDF partition is not complete, but writing/reading is implemented. Waiting for response.

**Comment by ericbusboom** [comment]
> On Oct 20, 2015, at 8:21 AM, Kazbek <notifications@github.com> wrote:
> 
> I added performance test:
> 
> py.test  tests/test_hdf_partitions/performance/test.py::Test::test_datafile_read_write  --capture=no
> HDF partition is not complete, but writing/reading is implemented. Waiting for response.

The performance looks pretty good — faster on writes but slower on reads. Go a head with the implementation. 

thanks, 

eric. 


----------------------------------------------------------------------------------------------------------
Eric Busboom                                                                                (619) 363 2607        
eric@busboom.org                                                         http://www.busboom.org

**Comment by nmb10** [comment]
Hi, Eric. I finished with implementation. There are two notes:

1. I'm not sure about column types/sizes I specified to store meta information. Can you check them? See hdf_partitions/core.py. I marked all of them with FIXME:

2. Current initialization of the hdf to load rows looks complicated:
```python
f = HDFPartition(...)
with f.writer as w:
    ri = RowIntuiter().run(source)
    ti = TypeIntuiter().process_header(ri.headers).run(source)
    w.set_row_spec(ri, ri.headers)
    w.set_types(ti)
f.load_rows(s)
```
Do you have any ideas how to simplify it?

**Comment by ericbusboom** [comment]
We can skip the Row and Type intuition for the HDF files. Since they are only output files, the types are set when they are creates, so the TypeIntuition can’t add an information. The RowIntuition isn’t necessary, since  HDF can’t have headers or footers in the same section as the data. 

However, it still needs the stats.

**Comment by ericbusboom** [comment]
Types for Schema:
- Start: 32 bit int is OK. 
- Flags: 32 char is probably large enough. It is currently unused. 
- LOM: 1 char
- Skew and Kurtosis. Float 64 is OK
- Hist is an array of 16 bins of integers. ( from Statset.num_bins )
- uvalues is 100 values of the same type as the column.

**Comment by ericbusboom** [comment]
Since hist and uvalues are array types, it is probably only possible to represent them with another dataset in the HDF file. So, there would be one more dataset of integers for every number column ( LOM = 'i' or 'r' for hist, and one dataset for every ordinal or nominal type ( LOM = 'o' or 'n' ) for the uvalues.

**Comment by ericbusboom** [comment]
HDFPartition.SCHEMA_TEMPLATE and HDFPartition.META_TEMPLATE should be shared from a common data structure with MPRowsFile.SCHEMA_TEMPLATE and MPRowsFile.META_TEMPLATE

**Comment by nmb10** [comment]
Done.
