### ISSUE TITLE
Import Geographic Shapefiles 

### ISSUE THREAD

**Issue by ericbusboom** [CivicKnowledge/ambry_sources#2]
Create a new subclass of sources.SourceFile to read geographic files. 

Use the fiona package to read the files, and shapely to turn the geographic data into WKT. Here is some example code: 

````python 
import fiona
from shapely.geometry import shape
from shapely.wkt import dumps, loads

with fiona.drivers():

    fn = 'zip:///Volumes/Storage/Downloads/Community_Plan_CN.zip'

    for i, layername in enumerate(fiona.listlayers('/',vfs=fn)):
            with fiona.open('/',vfs=fn,layer=i) as source:
                print(i, layername, len(source))
                
                geometry_type =  source.schema['geometry']
                property_schema = source.schema['properties']
                
                for s in source:
                    row_data =  s['properties']
                    shp = shape(s['geometry'])
                    wkt = dumps(shp)
````

(See  tests/test_data/geosources.csv for URLS of shapefiles you can download to use in the example )

To construct the the final schema for MPR file:

* The first column is an ``id`` field, taken from the ``id`` value of each shape
* The middle values are taken from the property_schema
* The last column is a string  named ``geometry``, which has the wkt value. However, the datatype for this column is ``geometry_type``

If the source spec has a ``segment``, the segment is the layer number. If there is no segment defined, assume the first layer. 

Testing
----------

Use the tests/test_data/geosources.csv as a source of SourceSpecs. Load it with basic_tests.py:load_sources(), and implement a functional test like basic_tests.py:test_row_load_intuit(). The geo files should all load properly via MPRowsFile.load_rows(s)

TODO
--------

The same class could also probably load other geo files, so it may be best to create a FionaSource(SourceFile) object, and then subclass for: shapefiles, GeoJSON, KML, etc.

**Comment by nmb10** [comment]
Can not load any shapefile:
```bash
$ wget http://public.source.civicknowledge.com.s3.amazonaws.com/example.com/geo/Community_Plan_CN.ZIP
```
Error 403: Forbidden.

Browser download:
```xml
<Error>
  <Code>AccessDenied</Code>
  <Message>Access Denied</Message>
  <RequestId>9166C6A2DF3AA762</RequestId>
  <HostId>txV8wio736cBbRmXOX9jh+luIlOlUSeyTKNNt6KwmNt8FPLSRvE+7el1m/4wVsyS</HostId>
</Error>
```

**Comment by ericbusboom** [comment]
FIxed. I added public permissions to all of the files in the directory.

**Comment by nmb10** [comment]
Why did you close it?

**Comment by ericbusboom** [comment]
Oh, sorry, I was thinking I closed the bug you mentioned in the comment.

**Comment by nmb10** [comment]
> The first column is an id field, taken from the id value of each shape
Shape does not contain id field

```python
shp = shape(s['geometry'])
print([x for x in dir(shp) if 'id' in x])
['centroid', 'is_valid']
```
Which field should I use for first column?

**Comment by ericbusboom** [comment]
> On Sep 18, 2015, at 10:10 AM, Kazbek <notifications@github.com> wrote:
> 
> The first column is an id field, taken from the id value of each shape
> Shape does not contain id field
> 
> shp = shape(s['geometry'
> ])
> 
> print([x for x in dir(shp) if 'id' in
>  x])
> [
> 'centroid', 'is_valid']
> Which field should I use for first column?

Look for one that has “ogr” or “fid” in it. “FID” stands for Feature ID and is a common id column name in GIS applications. 

If that doesn’t exist, make it and assign a sequential integer to it. 

eric. 

----------------------------------------------------------------------------------------------------------
Eric Busboom                                                                                (619) 363 2607        
eric@busboom.org                                                         http://www.busboom.org

**Comment by nmb10** [comment]
I don't see any. Here are all of them:

```python
(Pdb) pprint(dir(shp))
['__and__',
 '__array_interface__',
 '__class__',
 '__del__',
 '__delattr__',
 '__dict__',
 '__doc__',
 '__eq__',
 '__format__',
 '__geo_interface__',
 '__geom__',
 '__getattribute__',
 '__hash__',
 '__init__',
 '__module__',
 '__ne__',
 '__new__',
 '__or__',
 '__p__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__weakref__',
 '__xor__',
 '_crs',
 '_ctypes_data',
 '_geom',
 '_get_coords',
 '_is_empty',
 '_lgeos',
 '_ndim',
 '_other_owned',
 '_repr_svg_',
 '_set_coords',
 'almost_equals',
 'area',
 'array_interface',
 'array_interface_base',
 'boundary',
 'bounds',
 'buffer',
 'centroid',
 'contains',
 'convex_hull',
 'coords',
 'covers',
 'crosses',
 'ctypes',
 'difference',
 'disjoint',
 'distance',
 'empty',
 'envelope',
 'equals',
 'equals_exact',
 'geom_type',
 'geometryType',
 'has_z',
 'impl',
 'interpolate',
 'intersection',
 'intersects',
 'is_closed',
 'is_empty',
 'is_ring',
 'is_simple',
 'is_valid',
 'length',
 'overlaps',
 'parallel_offset',
 'project',
 'relate',
 'relate_pattern',
 'representative_point',
 'simplify',
 'svg',
 'symmetric_difference',
 'to_wkb',
 'to_wkt',
 'touches',
 'type',
 'union',
 'within',
 'wkb',
 'wkb_hex',
 'wkt',
 'xy']
```

**Comment by ericbusboom** [comment]
> On Sep 18, 2015, at 11:36 AM, Kazbek <notifications@github.com> wrote:
> 
> I don't see any. Here are all of them:

It isn’t a property of the shape object, it’s part of the data in the shapefile. 

What shapefile file are you using?

eric, 


----------------------------------------------------------------------------------------------------------
Eric Busboom                                                                                (619) 363 2607        
eric@busboom.org                                                         http://www.busboom.org

**Comment by nmb10** [comment]
http://public.source.civicknowledge.com.s3.amazonaws.com/example.com/geo/Roads_Highway.zip
This is how I load it
```python
sources = self.load_sources(file_name='geo_sources.csv')
spec = sources['highways']
s = get_source(spec, cache_fs)
```

**Comment by nmb10** [comment]
I've found 'id' key in the sources element.
```python
for s in source:
    print(s['id'])
0
1
2
3
4
```
Is it the value we are looking for?

**Comment by ericbusboom** [comment]
> On Sep 18, 2015, at 9:06 PM, Kazbek <notifications@github.com> wrote:
> 
> I've found 'id' key in the sources element.
> 
> Is it the value we are looking for?

Probably. It would be in the source, or the properties, not the shape. 

eric. 

----------------------------------------------------------------------------------------------------------
Eric Busboom                                                                                (619) 363 2607        
eric@busboom.org                                                         http://www.busboom.org

**Comment by nmb10** [comment]
Done.
