### ISSUE TITLE
Can't create virtual table if column is named 'index'

### ISSUE THREAD

**Issue by ericbusboom** [CivicKnowledge/ambry_sources#29]
When creating a virtual table where one of the columns is named 'index', the schema Source() (med/sqlite.py:162) can't be loaded because 'index' is a key word. The actual error appears in med/sqlite.py:112

**Comment by nmb10** [comment]
What do you do exactly to create a virtual table?
What is the expected behaviour? Rename or taboo?

**Comment by ericbusboom** [comment]
I added a regression test to exhibit the problem on the develop branch.

The solution is probably just to quote all of the column names in the table DDL. 

https://github.com/CivicKnowledge/ambry/blob/develop/test/regression/test_29_ambry_sources.py
