### ISSUE TITLE
ambry_source uses ambry methods. Replace them or add ambry to requirements.

### ISSUE THREAD

**Issue by nmb10** [CivicKnowledge/ambry_sources#3]
```bash
grep -r "from ambry.util"
```
ambry_sources/sources.py:            from ambry.util.flo import copy_file_or_flo
ambry_sources/download.py:    from ambry.util.flo import copy_file_or_flo
ambry_sources/download.py:    from ambry.util import parse_url_to_dict
ambry_sources/download.py:    from ambry.util import parse_url_to_dict

**Comment by ericbusboom** [comment]
> On Sep 11, 2015, at 10:07 PM, Kazbek <notifications@github.com> wrote:
> 
> grep -r "from ambry.util"
> ambry_sources/sources.py: from ambry.util.flo import copy_file_or_flo
> ambry_sources/download.py: from ambry.util.flo import copy_file_or_flo
> ambry_sources/download.py: from ambry.util import parse_url_to_dict
> ambry_sources/download.py: from ambry.util import parse_url_to_dict

Copy them over. They are both pretty small. 

eric. 

----------------------------------------------------------------------------------------------------------
Eric Busboom                                                                                (619) 363 2607        
eric@busboom.org                                                         http://www.busboom.org

**Comment by nmb10** [comment]
Done.
