### ISSUE TITLE
Higher Performance Date Conversion

### ISSUE THREAD

**Issue by ericbusboom** [CivicKnowledge/ambry_sources#7]
The current method of handling dates is spectacularly slow. Compare the read and write speed of test_basic.py:test_datafile_read_write() using rand_date_b() vs rand_date_a()

To improve this, alter the ambry_sources.mpf.MPRowsFile#encode_obj and decode_obj to convert dates to numbers before storage. The fastest method is probably to write them as tuples, so a time HH:MM:SS is written as (HH,MM,SS)

**Comment by nmb10** [comment]
Done.

Before fix (store as str):
```
('MSGPack write L', 29289.472419892045, 50000)
('MSGPack write S', 5832.266062431705, 50000)
('MSGPack read   ', 10498.828942267335, 49999, 50000, 0)
('MSGPack rows   ', 10658.526724305957)
('MSGPack raw    ', 10683.61684469791)
```
After fix (store as tuple):
```
('MSGPack write L', 29788.608536736763, 50000)
('MSGPack write S', 6071.09621344485, 50000)
('MSGPack read   ', 103316.02164109325, 49999, 50000, 0)
('MSGPack rows   ', 111084.67354490684)
('MSGPack raw    ', 110289.58251818568)
```

**Comment by ericbusboom** [comment]
> On Nov 7, 2015, at 6:42 AM, Kazbek <notifications@github.com> wrote:
> 
> Done.
> 
> Before fix (store as str):
> 
> After fix (store as tuple):

Wow! 

eric. 

----------------------------------------------------------------------------------------------------------
Eric Busboom                                                                                (619) 363 2607        
eric@busboom.org                                                         http://www.busboom.org
